"""

Revision ID: 4a5c286afcfa
Revises: a84554b7ca53
Create Date: 2026-02-22 20:45:23.644857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a5c286afcfa'
down_revision = 'a84554b7ca53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('showlists',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner_user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('spotify_playlist_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('showlist_shows',
    sa.Column('showlist_id', sa.String(), nullable=False),
    sa.Column('show_id', sa.String(), nullable=False),
    sa.Column('added_at', sa.String(), nullable=False),
    sa.Column('added_by_user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ),
    sa.ForeignKeyConstraint(['showlist_id'], ['showlists.id'], ),
    sa.PrimaryKeyConstraint('showlist_id', 'show_id')
    )
    op.drop_table('playlist_shows')
    op.drop_table('playlists')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlists',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('owner_user_id', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.VARCHAR(), nullable=False),
    sa.Column('spotify_playlist_id', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playlist_shows',
    sa.Column('playlist_id', sa.VARCHAR(), nullable=False),
    sa.Column('show_id', sa.VARCHAR(), nullable=False),
    sa.Column('added_at', sa.VARCHAR(), nullable=False),
    sa.Column('added_by_user_id', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ),
    sa.PrimaryKeyConstraint('playlist_id', 'show_id')
    )
    op.drop_table('showlist_shows')
    op.drop_table('showlists')
    # ### end Alembic commands ###
